export const MATH_FUNCTIONS = [
    {
        name: 'lengthA',
        always: false,
        usesTime: false,
        body: `vec4 lengthA(vec4 a) { return vec4(length(a)); }`,
        weight: 1.5,
    },
    {
        name: 'asinA',
        always: false,
        usesTime: false,
        body: `vec4 asinA(vec4 a) { return asin(clamp(a,-1.,1.)); }`,
        weight: 0.5,
    },
    {
        name: 'acosA',
        always: false,
        usesTime: false,
        body: `vec4 acosA(vec4 a) { return acos(clamp(a,-1.,1.)); }`,
        weight: 0.5,
    },
    {
        name: 'logA',
        always: false,
        usesTime: false,
        body: `vec4 logA(vec4 a) { return log(abs(a)+1e-5); }`,
        weight: 0.3,
    },
    {
        name: 'log2A',
        always: false,
        usesTime: false,
        body: `vec4 log2A(vec4 a) { return log2(abs(a)+1e-5); }`,
        weight: 0.3,
    },
    {
        name: 'sqrtA',
        always: false,
        usesTime: false,
        body: `vec4 sqrtA(vec4 a) { return sqrt(abs(a)); }`,
        weight: 1.2,
    },
    {
        name: 'inversesqrtA',
        always: false,
        usesTime: false,
        body: `vec4 inversesqrtA(vec4 a) { return inversesqrt(abs(a)+1e-5); }`,
        weight: 0.4,
    },
    {
        name: 'pow2',
        always: false,
        usesTime: false,
        body: `vec4 pow2(vec4 a) { return a*a; }`,
        weight: 2.0,
    },
    {
        name: 'pow3',
        always: false,
        usesTime: false,
        body: `vec4 pow3(vec4 a) { return a*a*a; }`,
        weight: 1.0,
    },
    {
        name: 'pow4',
        always: false,
        usesTime: false,
        body: `vec4 pow4(vec4 a) { vec4 b=a*a; return b*b; }`,
        weight: 0.8,
    },
    {
        name: 'smoothA',
        always: false,
        usesTime: false,
        body: `vec4 smoothA(vec4 a) { return smoothstep(vec4(0.),vec4(1.),a); }`,
        weight: 1.2,
    },
    {
        name: 'smoothclampA',
        always: false,
        usesTime: false,
        body: `vec4 smoothclampA(vec4 a) { return clamp(a*a*(3.-2.*a),0.,1.); }`,
        weight: 1.0,
    },
];
